import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Light mode surfaces
        "primary": "#765a00",
        "on-primary": "#ffffff",
        "primary-container": "#e1b952",
        "on-primary-container": "#614900",
        "primary-fixed": "#ffdf95",
        "primary-fixed-dim": "#eac25a",
        "on-primary-fixed": "#251a00",
        "on-primary-fixed-variant": "#594400",
        "secondary": "#5f5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2dfde",
        "on-secondary-container": "#636262",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1b1b1c",
        "on-secondary-fixed-variant": "#474746",
        "tertiary": "#5d5e5f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#bebebe",
        "on-tertiary-container": "#4c4d4d",
        "tertiary-fixed": "#e3e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#fff8f1",
        "on-background": "#201b11",
        "surface": "#fff8f1",
        "on-surface": "#201b11",
        "surface-dim": "#e3d9c9",
        "surface-bright": "#fff8f1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fdf2e2",
        "surface-container": "#f7eddc",
        "surface-container-high": "#f1e7d7",
        "surface-container-highest": "#ebe1d1",
        "surface-variant": "#ebe1d1",
        "on-surface-variant": "#4d4636",
        "surface-tint": "#765a00",
        "outline": "#7f7664",
        "outline-variant": "#d1c5b1",
        "inverse-surface": "#353025",
        "inverse-on-surface": "#faefdf",
        "inverse-primary": "#eac25a",
        // Dark mode overrides
        "dark-surface": "#1a1814",
        "dark-surface-container": "#252219",
        "dark-surface-container-high": "#302c22",
        "dark-surface-container-highest": "#3b362b",
        "dark-on-surface": "#faefdf",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
